function enterInitialState() {
    page.transitionRect.visible = false
    page.previousRect.visible = false
    page.nextRect.visible = false
    page.fullScreenRect.visible = false
    page.fitZoomRect.visible = false
    page.fitScreenRect.visible = false
    page.zoomInRect.visible = false
    page.zoomOutRect.visible = false
    page.drawRect.visible = false
    page.toolRect.visible = false
    page.fileRect.visible = false
    page.fileLabel.visible = false
    page.fileToolRect.visible = false
    page.canvasMouseArea.preventStealing = false
    page.drawRect.border.color = "transparent"
    page.drawRect.border.width = 0
    page.fileRect.border.color = "transparent"
    page.fileRect.border.width = 0
    page.textRect.visible = false
    page.textRect.border.color = "transparent"
    page.textRect.border.width = 0
}

function enterShowToolState() {
    page.transitionRect.visible = true
    page.previousRect.visible = true
    page.nextRect.visible = true
    page.fullScreenRect.visible = true
    page.fitZoomRect.visible = true
    page.fitScreenRect.visible = true
    page.zoomInRect.visible = true
    page.zoomOutRect.visible = true
    page.drawRect.visible = true
    page.toolRect.visible = false
    page.fileRect.visible = true
    page.fileLabel.visible = true
    page.textRect.visible = true
    page.fileToolRect.visible = false
    page.canvasMouseArea.cursorShape = Qt.ArrowCursor
}

function enterDrawState() {
    page.transitionRect.visible = false
    page.previousRect.visible = false
    page.nextRect.visible = false
    page.fullScreenRect.visible = false
    page.fitZoomRect.visible = false
    page.fitScreenRect.visible = false
    page.zoomInRect.visible = false
    page.zoomOutRect.visible = false
    page.drawRect.visible = true
    page.toolRect.visible = true
    page.fileRect.visible = false
    page.fileLabel.visible = false
    page.canvasMouseArea.preventStealing = true
    page.canvasMouseArea.cursorShape = Qt.PointingHandCursor
    page.drawRect.border.color = window.color
    page.drawRect.border.width = 8
    page.textRect.visible = false
}

function enterFileState() {
    page.transitionRect.visible = false
    page.previousRect.visible = false
    page.nextRect.visible = false
    page.fullScreenRect.visible = false
    page.fitZoomRect.visible = false
    page.fitScreenRect.visible = false
    page.zoomInRect.visible = true
    page.zoomOutRect.visible = true
    page.drawRect.visible = false
    page.toolRect.visible = false
    page.fileRect.visible = true
    page.fileLabel.visible = true
    page.fileToolRect.visible = true
    page.fileRect.border.color = window.color
    page.fileRect.border.width = 8
}
